# Generated by Django 5.1.2 on 2024-10-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_pt',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
